// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK-409O2xX0djhm9UNscDcGWqgwC4fL9o',
    appId: '1:770338205046:web:579aaa4686c930860c1e57',
    messagingSenderId: '770338205046',
    projectId: 'rentzy-8208b',
    authDomain: 'rentzy-8208b.firebaseapp.com',
    storageBucket: 'rentzy-8208b.firebasestorage.app',
    measurementId: 'G-SXJS2F73ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd2RqURdThJv8qV6FQm5sNFoz_5hWTNSs',
    appId: '1:770338205046:android:61c527d4b7db3e730c1e57',
    messagingSenderId: '770338205046',
    projectId: 'rentzy-8208b',
    storageBucket: 'rentzy-8208b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDHluB10BDrLDzU5fe_NCdWFJbhiMPk1c',
    appId: '1:770338205046:ios:450f435ac6c88c320c1e57',
    messagingSenderId: '770338205046',
    projectId: 'rentzy-8208b',
    storageBucket: 'rentzy-8208b.firebasestorage.app',
    iosBundleId: 'com.example.rentzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDHluB10BDrLDzU5fe_NCdWFJbhiMPk1c',
    appId: '1:770338205046:ios:450f435ac6c88c320c1e57',
    messagingSenderId: '770338205046',
    projectId: 'rentzy-8208b',
    storageBucket: 'rentzy-8208b.firebasestorage.app',
    iosBundleId: 'com.example.rentzy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK-409O2xX0djhm9UNscDcGWqgwC4fL9o',
    appId: '1:770338205046:web:27886b62c4d3d5220c1e57',
    messagingSenderId: '770338205046',
    projectId: 'rentzy-8208b',
    authDomain: 'rentzy-8208b.firebaseapp.com',
    storageBucket: 'rentzy-8208b.firebasestorage.app',
    measurementId: 'G-2CDBVNJSVC',
  );
}
